/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.itla.vista;

import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ideapad
 */
public class ContactoVista extends javax.swing.JFrame {

    /**
     * Creates new form ContactoVista
     */
    public ContactoVista() {
        initComponents();
        
        // Centrar el jFRame
        setLocationRelativeTo(null);
        
        // Cambiemos el color de fondo
        getContentPane().setBackground(Color.WHITE);
    }
    
     public String getTxtSearchId() {
        return txtSearchId.getText();
    }

    public void setTxtSearchId(String text) {
        this.txtSearchId.setText(text);
    }

    public String getTxtName1() {
        return txtName1.getText();
    }

    public void setTxtName1(String text) {
        this.txtName1.setText(text);
    }

    public String getTxtLastName() {
        return txtLastName.getText();
    }

    public void setTxtLastName(String text) {
        this.txtLastName.setText(text);
    }

    public String getTxtEmail() {
        return txtEmail.getText();
    }

    public void setTxtEmail(String text) {
        this.txtEmail.setText(text);
    }

    public String getTxtTel() {
        return txtTel.getText();
    }

    public void setTxtTel(String text) {
        this.txtTel.setText(text);
    }

    public String getJTextCompany() {
        return jTextCompany.getText();
    }

    public void setJTextCompany(String text) {
        this.jTextCompany.setText(text);
    }

    public void addSearchIdListener(ActionListener listener) {
        btnSearchId.addActionListener(listener);
    }

    public void addAddContactListener(ActionListener listener) {
        btnAddContact.addActionListener(listener);
    }
    
    public void addListarTodosListener(ActionListener listener) {
        btnListarTodos.addActionListener(listener);
    }


    public DefaultTableModel getTableModel() {
        return (DefaultTableModel) tblContact.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextCompany = new LIB.FSTexFieldMD();
        jLabel3 = new javax.swing.JLabel();
        txtName1 = new LIB.FSTexFieldMD();
        txtLastName = new LIB.FSTexFieldMD();
        txtEmail = new LIB.FSTexFieldMD();
        txtSearchId = new LIB.FSTexFieldMD();
        rSScrollPane1 = new necesario.RSScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContact = new rojerusan.RSTableMetro();
        txtTel = new LIB.FSTexFieldMD();
        jLabel2 = new javax.swing.JLabel();
        btnSearchId = new rojeru_san.rsbutton.RSButtonRound();
        btnAddContact = new rojeru_san.rsbutton.RSButtonRound();
        btnListarTodos = new rojeru_san.rsbutton.RSButtonRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 113, 181));
        jLabel1.setText("Buscar contacto");

        jTextCompany.setForeground(new java.awt.Color(0, 113, 181));
        jTextCompany.setBordeColorFocus(new java.awt.Color(0, 113, 181));
        jTextCompany.setFont(new java.awt.Font("Roboto Bold", 0, 18)); // NOI18N
        jTextCompany.setPlaceholder("Empresa");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (3).png"))); // NOI18N

        txtName1.setForeground(new java.awt.Color(0, 113, 181));
        txtName1.setBordeColorFocus(new java.awt.Color(0, 113, 181));
        txtName1.setFont(new java.awt.Font("Roboto Bold", 0, 18)); // NOI18N
        txtName1.setPlaceholder("Nombre");

        txtLastName.setForeground(new java.awt.Color(0, 113, 181));
        txtLastName.setBordeColorFocus(new java.awt.Color(0, 113, 181));
        txtLastName.setFont(new java.awt.Font("Roboto Bold", 0, 18)); // NOI18N
        txtLastName.setPlaceholder("Apellidos");

        txtEmail.setForeground(new java.awt.Color(0, 113, 181));
        txtEmail.setBordeColorFocus(new java.awt.Color(0, 113, 181));
        txtEmail.setFont(new java.awt.Font("Roboto Bold", 0, 18)); // NOI18N
        txtEmail.setPlaceholder("Correo");

        txtSearchId.setForeground(new java.awt.Color(0, 113, 181));
        txtSearchId.setBordeColorFocus(new java.awt.Color(0, 113, 181));
        txtSearchId.setFont(new java.awt.Font("Roboto Bold", 0, 18)); // NOI18N
        txtSearchId.setPlaceholder("id");

        tblContact.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellidos", "Correo", "Telefono", "Empresa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblContact.setColorFilasBackgound2(new java.awt.Color(225, 225, 225));
        tblContact.setFuenteFilasSelect(new java.awt.Font("Roboto Bold", 0, 14)); // NOI18N
        tblContact.setFuenteHead(new java.awt.Font("Roboto Bold", 0, 18)); // NOI18N
        tblContact.setFuenteHover(new java.awt.Font("Roboto Bold", 0, 14)); // NOI18N
        tblContact.setGridColor(new java.awt.Color(232, 232, 232));
        jScrollPane1.setViewportView(tblContact);

        rSScrollPane1.setViewportView(jScrollPane1);

        txtTel.setForeground(new java.awt.Color(0, 113, 181));
        txtTel.setBordeColorFocus(new java.awt.Color(0, 113, 181));
        txtTel.setFont(new java.awt.Font("Roboto Bold", 0, 18)); // NOI18N
        txtTel.setPlaceholder("Teléfono");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 113, 181));
        jLabel2.setText("Gestión de Contactos");

        btnSearchId.setText("Buscar");

        btnAddContact.setText("Agregar Contacto");

        btnListarTodos.setText("Listar todos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAddContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(180, 180, 180))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSearchId, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearchId, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnListarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addGap(27, 27, 27))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rSScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(94, 94, 94)
                            .addComponent(jLabel3))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(105, 105, 105)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSearchId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnSearchId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnListarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rSScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(jTextCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactoVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.rsbutton.RSButtonRound btnAddContact;
    private rojeru_san.rsbutton.RSButtonRound btnListarTodos;
    private rojeru_san.rsbutton.RSButtonRound btnSearchId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private LIB.FSTexFieldMD jTextCompany;
    private necesario.RSScrollPane rSScrollPane1;
    private rojerusan.RSTableMetro tblContact;
    private LIB.FSTexFieldMD txtEmail;
    private LIB.FSTexFieldMD txtLastName;
    private LIB.FSTexFieldMD txtName1;
    private LIB.FSTexFieldMD txtSearchId;
    private LIB.FSTexFieldMD txtTel;
    // End of variables declaration//GEN-END:variables
}
